# Compose file used for local development

---
version: "3.8"
services:
  # Could use .env file here as a nice-to-have
  api:
    tty: true
    build:
      context: .
      target: build
    networks:
      - database
    ports:
      - "3000:3000"

    # 'database' service registered in /etc/hosts due to shared network
    environment:
      APP_HOST: '0.0.0.0'
      DB_HOST: "database"
      DB_PASS: "dev_password"
      DB_USER: "dev_user"

    volumes:
      - node_modules:/app/node_modules

  database:
    tty: true
    image: postgres:15.0
    networks:
      - database
    ports:
      - "5432:5432"

    environment:
      USER_PASSWORD: "dev_password"
      POSTGRES_PASSWORD: "dev_password"

    volumes:
      # init SQL
      - ./data/init.sh:/docker-entrypoint-initdb.d/init.sh
      - data:/var/lib/postgresql/data

networks:
  database:

volumes:
  data:
  node_modules:
