-- Initialization SQL for proof-of-concept 'items' table.
-- NOTE: Proper migrations/schemata should be defined when requirements are
-- better understood.

-- Owned by superuser
CREATE DATABASE proj_purple_cow;

-- Create schema ppc, items table
CREATE SCHEMA IF NOT EXISTS ppc;

CREATE TABLE items (
  id    INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name  TEXT
);

CREATE USER dev_user WITH password 'dev_password';

GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON items TO dev_user;
